source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
gem 'nokogiri', '~> 1.13.3'
gem 'rubyzip', '~> 2.3.2'
gem 'jekyll-theme-merlot', '~> 0.2.0'
gem 'jekyll-theme-midnight', '~> 0.2.0'
gem 'jekyll-theme-tactile', '~> 0.2.0'